apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastify-server
  namespace: node-drain
  labels:
    app: fastify_server
spec:
  replicas: 10
  selector:
    matchLabels:
      app: fastify_server
  template:
    metadata:
      labels:
        app: fastify_server
    spec:
      containers:
        - name: fastify-server
          image: gkabitakis/node-drain-example:1.0.0
          resources:
            requests:
              memory: '250Mi'
              cpu: '0.2'
            limits:
              memory: '300Mi'
              cpu: '0.4'
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: fastify-server
  namespace: node-drain
spec:
  selector:
    app: fastify_server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
